# Generated by Django 2.2.6 on 2019-10-19 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_auto_20191017_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='to',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='to_message', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
